# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: discourse
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/discourse:3.5.0-debian-12-r1
    - name: os-shell
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 3.5.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.X.X
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.X.X
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Discourse is an open source discussion platform with built-in moderation
  and governance systems that let discussion communities protect themselves from bad
  actors even without official moderators.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/discourse/img/discourse-stack-220x234.png
keywords:
- community
- forum
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
- email: username.taken@gmail.com
  name: paulczar
- email: preteluca@gmail.com
  name: lucaprete
name: discourse
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/discourse
version: 17.0.4
