# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: apache-exporter
      version: 1.0.10
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/apache-exporter:1.0.10-debian-12-r57
    - name: moodle
      version: 5.0.2
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/moodle:5.0.2-debian-12-r4
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r52
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.0.2
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Moodle(TM) LMS is an open source online Learning Management System widely
  used at universities, schools, and corporations. It is modular and highly adaptable
  to any type of online learning.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/moodle/img/moodle-stack-220x234.png
keywords:
- moodle
- learning
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: moodle
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/moodle
version: 28.0.4
