# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: airflow
      version: 3.1.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/airflow:3.1.0-debian-12-r0
    - name: statsd-exporter
      version: 0.28.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/statsd-exporter:0.28.0-debian-12-r26
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 3.1.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 18.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Airflow is a tool to express and execute workflows as directed
  acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress
  and handle task dependencies.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 26.0.0
