# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kubectl
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/kubectl:1.34.0-debian-12-r1
    - name: mongodb
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/mongodb:8.0.13-debian-12-r0
    - name: mongodb-exporter
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/mongodb-exporter:0.47.0-debian-12-r1
    - name: nginx
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/nginx:1.29.1-debian-12-r0
    - name: os-shell
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.0.13
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it
  stores data in JSON-like documents. Automated scalability and high-performance.
  Ideal for developing cloud native applications.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mongodb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mongodb
version: 17.0.2
