# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: minio
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/minio:2025.7.23-debian-12-r7
    - name: minio-client
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/minio-client:2025.8.13-debian-12-r0
    - name: minio-object-browser
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/minio-object-browser:2.0.4-debian-12-r0
    - name: os-shell
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r52
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 2025.7.23
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
  storage service, mainly used for storing unstructured data (such as photos, videos,
  log files, etc.).
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: minio
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/minio
version: 17.0.27
